
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.String.format;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Leonardy
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        if (loadJurnal > 10) {
            loadJurnal = 1;
        }
        dMenuJurnal.getContentPane().setBackground(new java.awt.Color(248, 238, 160));
        dEditorJurnal.getContentPane().setBackground(new java.awt.Color(248, 238, 160));
        jPanel4.setVisible(false);
        add(new Detail(), BorderLayout.PAGE_START);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        dMenuJurnal = new javax.swing.JDialog();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        dEditorJurnal = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setBackground(new java.awt.Color(248, 238, 160));
        jMenuItem1.setText("jMenuItem1");

        dMenuJurnal.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dMenuJurnal.setForeground(new java.awt.Color(102, 255, 204));
        dMenuJurnal.setLocation(new java.awt.Point(400, 300));
        dMenuJurnal.setMinimumSize(new java.awt.Dimension(470, 370));
        dMenuJurnal.setModal(true);

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton13.setText("CREATE NEW JURNAL");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton14.setText("USE EXCISTING JURNAL");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton15.setText("CANCEL");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dMenuJurnalLayout = new javax.swing.GroupLayout(dMenuJurnal.getContentPane());
        dMenuJurnal.getContentPane().setLayout(dMenuJurnalLayout);
        dMenuJurnalLayout.setHorizontalGroup(
            dMenuJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dMenuJurnalLayout.createSequentialGroup()
                .addGroup(dMenuJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dMenuJurnalLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(dMenuJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(dMenuJurnalLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton15)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        dMenuJurnalLayout.setVerticalGroup(
            dMenuJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dMenuJurnalLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButton13)
                .addGap(30, 30, 30)
                .addComponent(jButton14)
                .addGap(28, 28, 28)
                .addComponent(jButton15)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        dEditorJurnal.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dEditorJurnal.setBackground(new java.awt.Color(248, 238, 160));
        dEditorJurnal.setLocation(new java.awt.Point(470, 370));
        dEditorJurnal.setMinimumSize(new java.awt.Dimension(400, 300));
        dEditorJurnal.setModal(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("CREATE NEW JURNAL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("YEAR");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("MONTH");

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton16.setText("CREATE");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton17.setText("CANCEL");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dEditorJurnalLayout = new javax.swing.GroupLayout(dEditorJurnal.getContentPane());
        dEditorJurnal.getContentPane().setLayout(dEditorJurnalLayout);
        dEditorJurnalLayout.setHorizontalGroup(
            dEditorJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dEditorJurnalLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(dEditorJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dEditorJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dEditorJurnalLayout.createSequentialGroup()
                            .addGroup(dEditorJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(dEditorJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel1))
                    .addGroup(dEditorJurnalLayout.createSequentialGroup()
                        .addComponent(jButton16)
                        .addGap(124, 124, 124)))
                .addGap(152, 152, 152))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dEditorJurnalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton17)
                .addGap(131, 131, 131))
        );
        dEditorJurnalLayout.setVerticalGroup(
            dEditorJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dEditorJurnalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(dEditorJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dEditorJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(dEditorJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton16))
                .addGap(26, 26, 26))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daricle");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1600, 900));

        jPanel1.setBackground(new java.awt.Color(237, 206, 162));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton1.setText("Home");
        buttonGroup1.add(jButton1);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton2.setText("Product");
        buttonGroup1.add(jButton2);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton3.setText("customer");
        buttonGroup1.add(jButton3);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton5.setText("inventory");
        buttonGroup1.add(jButton5);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton6.setText("jurnal");
        buttonGroup1.add(jButton6);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton7.setText("General Ledger");
        jButton7.setBorderPainted(false);
        buttonGroup1.add(jButton7);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton8.setText("Trial Balance");
        buttonGroup1.add(jButton8);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton9.setText("Profit Loss");
        buttonGroup1.add(jButton9);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton10.setText("report");
        buttonGroup1.add(jButton10);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton11.setText("Chart");
        buttonGroup1.add(jButton11);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton12.setText("Jurnal view");
        buttonGroup1.add(jButton12);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton4.setText("supplier");
        buttonGroup1.add(jButton4);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton18.setText("INVOICE");
        buttonGroup1.add(jButton18);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(16, 16, 16)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(248, 238, 160));
        jPanel2.setPreferredSize(new java.awt.Dimension(1300, 700));

        jLabel4.setFont(new java.awt.Font("SimSun", 3, 140)); // NOI18N
        jLabel4.setText("Daricle");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel5.setText("Accounting");

        jLabel6.setText("Copyright @ 2017 Darile Accounting");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel4)
                .addGap(0, 443, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(67, 67, 67))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(248, 238, 160));
        jPanel4.setPreferredSize(new java.awt.Dimension(1145, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addGap(379, 379, 379)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(596, 596, 596))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(66, 30));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem2.setText("New Jurnal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem3.setText("Open Jurnal");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem4.setText("FORMAT");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Product product = new Product();
    Supplier supplier = new Supplier();
    Customer customer = new Customer();
    Jurnal jurnal = new Jurnal();
    Chart chart = new Chart();
    JurnalView jurnalview = new JurnalView();
    GeneralLedger generalledger = new GeneralLedger();
    TrialBallance trialballance = new TrialBallance();
    Inventory inventory = new Inventory();
    ProfitLoss profitLoss = new ProfitLoss();
    BalanceSheet balanceSheet = new BalanceSheet();
    Detail detail = new Detail();
    Invoice invoice = new Invoice();

    int menu = 0;
    int loadJurnal = 0;

    public void homeButton() {
        jPanel2.setVisible(false);
        customer.setVisible(false);
        product.setVisible(false);
        supplier.setVisible(false);
        jurnal.setVisible(false);
        chart.setVisible(false);
        jurnalview.setVisible(false);
        generalledger.setVisible(false);
        trialballance.setVisible(false);
        inventory.setVisible(false);
        profitLoss.setVisible(false);
        balanceSheet.setVisible(false);
        invoice.setVisible(false);
    }

//    public void setIcon(String detail) {
////        this.//////detail.setJurnalDetail(detail);
//    }
    public void ChangeIcon() {
        if (menu == 0) {
            jLabel1.setText("CREATE NEW JURNAL");
            jButton16.setText("CREATE");
        }
        if (menu == 1) {
            jLabel1.setText("EXCISTING JURNAL");
            jButton16.setText("ENTER");
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        homeButton();
        add(product, BorderLayout.CENTER);
        product.setVisible(true);
//        setIcon("", "PRODUCT");
        Detail.setIconDetail("PRODUCT");
        //icon detail
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
        //
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        homeButton();
        add(customer, BorderLayout.CENTER);
        customer.setVisible(true);
//        setIcon("", "CUSTOMER");
        Detail.setIconDetail("CUSTOMER");
        //icon detail
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
        //
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        homeButton();
        jPanel2.setVisible(true);
//        setIcon("", "");
        Detail.setIconDetail("");
        //icon detail
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
        //
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        homeButton();
        add(supplier, BorderLayout.CENTER);
        supplier.setVisible(true);
//        setIcon("", "SUPPLIER");
        Detail.setIconDetail("SUPPLIER");
        //icon detail
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
        //

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Detail.setIconDetail("");
//        setIcon("", "");
        if (loadJurnal > 0) {
            homeButton();
            add(jurnal, BorderLayout.CENTER);
            jurnal.setVisible(true);
//            setIcon("", "JURNAL");
            Detail.setIconDetail("JURNAL");
            //icon detail
            Detail.setCash(DataBase.date);
            Detail.setBank(DataBase.date);
            //
        } else {
            homeButton();
            add(jPanel2, BorderLayout.CENTER);
            dMenuJurnal.setLocationRelativeTo(null);
            dMenuJurnal.setVisible(true);
//            setIcon("", "");
//            Detail.setIconDetail("");
            loadJurnal++;
            //icon detail
            Detail.setCash(DataBase.date);
            Detail.setBank(DataBase.date);
            //
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        homeButton();
        add(chart, BorderLayout.CENTER);
        chart.setVisible(true);
//        setIcon("", "CHART");
        Detail.setIconDetail("CHART");
        //icon detail
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
        //
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        homeButton();
        add(jurnalview, BorderLayout.CENTER);
        jurnalview.setVisible(true);
        jurnalview.setTf();
//        setIcon("", "VIEW JURNAL");
        Detail.setIconDetail("VIEW JURNAL");
        //icon detail
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
        //

    }//GEN-LAST:event_jButton12ActionPerformed

//for jurnal dialog menu
    //create bttuon
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        dEditorJurnal.setLocationRelativeTo(null);
        dMenuJurnal.setVisible(false);
        ChangeIcon();
        dEditorJurnal.setVisible(true);

    }//GEN-LAST:event_jButton13ActionPerformed
    //enter menu
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        menu = 1;
        ChangeIcon();
        dEditorJurnal.setLocationRelativeTo(null);
        dMenuJurnal.setVisible(false);
        dEditorJurnal.setVisible(true);

    }//GEN-LAST:event_jButton14ActionPerformed
    //cancel dmenu button
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        menu = 0;
        dMenuJurnal.setVisible(false);
        ChangeIcon();
        loadJurnal--;
    }//GEN-LAST:event_jButton15ActionPerformed

//ok button dialog editor
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (menu == 0) { //create new jurnal
            dEditorJurnal.setVisible(false);
            DataBase.setExecuteUpdate("INSERT INTO SYSTEM(system_date, system_jurnal, system_sales, system_pur, system_pay) VALUES('" + jTextField1.getText()
                    + "-" + jTextField2.getText() + "-1',1,1,1,1)");
            System.out.println("INSERT INTO SYSTEM(system_date, system_jurnal, system_sales, system_pur,system_pay) VALUES('" + jTextField1.getText()
                    + "-" + jTextField2.getText() + "-1',1,1,1,1)");

            DataBase.date = jTextField1.getText() + "-" + jTextField2.getText();
            DataBase.jurnalDate = jTextField1.getText() + "-" + jTextField2.getText();
            DataBase.jurnalId = 1;
            DataBase.salesId = 1;
            DataBase.purId = 1;
            DataBase.payId = 1;
            loadJurnal++;
            System.out.println(DataBase.date);
            homeButton();
//            setIcon("DATE : " + DataBase.jurnalDate, "JURNAL");
            //icon detail
            Detail.setCash(DataBase.date);
            Detail.setBank(DataBase.date);
            //
            add(jurnal, BorderLayout.CENTER);
            jurnal.setVisible(true);
            Detail.setIconDetail("JURNAL");
            Detail.setJurnalDateDetail("DATE : " + DataBase.date);

        }
        if (menu == 1) { // use existing juranl
            dEditorJurnal.setVisible(false);

            DataBase.date = jTextField1.getText() + "-" + jTextField2.getText();
            DataBase.jurnalDate = jTextField1.getText() + "-" + jTextField2.getText();
            DataBase.setJurnalId();
            loadJurnal++;

            System.out.println(DataBase.date);
            homeButton();
//            setIcon("DATE : " + DataBase.jurnalDate, "JURNAL");
            //icon detail
            Detail.setCash(DataBase.date);
            Detail.setBank(DataBase.date);
            //
            add(jurnal, BorderLayout.CENTER);
            jurnal.setVisible(true);
            Detail.setIconDetail("JURNAL");
            Detail.setJurnalDateDetail("DATE : " + DataBase.date);

        }
    }//GEN-LAST:event_jButton16ActionPerformed
//cancel deditor button
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        menu = 0;
        dEditorJurnal.setVisible(false);
        dMenuJurnal.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        homeButton();
        add(generalledger, BorderLayout.CENTER);
        generalledger.setVisible(true);
        generalledger.setTf();
        Detail.setIconDetail("GENERAL LEDGER");
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
//        setIcon("", "GENERAL LEDGER");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        homeButton();
        add(trialballance, BorderLayout.CENTER);
        trialballance.setVisible(true);
        trialballance.setTf();
        Detail.setIconDetail("TRIAL BALANCE");
        //icon detail
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
        //
//        setIcon("", "TRIAL BALANCE");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        homeButton();
        add(inventory, BorderLayout.CENTER);
        inventory.setVisible(true);
        inventory.setTf();
        Detail.setIconDetail("INVENTORY");
        //icon detail
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
        //
//        setIcon("", "INVENTORY");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        homeButton();
        add(profitLoss, BorderLayout.CENTER);
        profitLoss.setVisible(true);
        profitLoss.setTf();
//        setIcon("", "PROFIT LOSS");
        Detail.setIconDetail("PROFIT LOSS");
        //icon detail
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
        //
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        homeButton();
        add(balanceSheet, BorderLayout.CENTER);
        balanceSheet.setVisible(true);
        balanceSheet.setTf();
        Detail.setIconDetail("BALANCE SHEET");
        //icon detail
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
        //
//        setIcon("", "BALANCE SHEET");

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        homeButton();
        dMenuJurnal.setVisible(true);
        Detail.setIconDetail("");
//        setIcon("", "");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        homeButton();
        dMenuJurnal.setVisible(true);
        Detail.setIconDetail("");
//        setIcon("", "");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            int check = JOptionPane.showConfirmDialog(this, "ARE YOU WANT DELETE ALL EXCEPT CHART, SUPPLIER AND CUSTOMER ?");
            if (check == JOptionPane.YES_OPTION) {
                DataBase.setExecuteUpdate("TRUNCATE TABLE JURNAL");
                DataBase.setExecuteUpdate("TRUNCATE TABLE SYSTEM");
                DataBase.setExecuteUpdate("TRUNCATE TABLE INVENTORY");
                DataBase.setExecuteUpdate("TRUNCATE TABLE INVOICE");
                DataBase.setExecuteUpdate("TRUNCATE TABLE PAYMENT");
                JOptionPane.showMessageDialog(this, "FORMAT SUCCESS");
                loadJurnal = 0;
                homeButton();
                jPanel2.setVisible(true);
                Detail.setIconDetail("");
                loadJurnal = 0;
                dEditorJurnal.setVisible(false);
                dMenuJurnal.setVisible(false);
//                setIcon("", "");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        homeButton();
        add(invoice, BorderLayout.CENTER);
        invoice.setVisible(true);
        invoice.setTf();
        Detail.setIconDetail("INVOICE");
        //icon detail
        Detail.setCash(DataBase.date);
        Detail.setBank(DataBase.date);
        //
//        setIcon("", "INVOICE");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        if (menu == 0) { //create new jurnal
            dEditorJurnal.setVisible(false);
            DataBase.setExecuteUpdate("INSERT INTO SYSTEM(system_date, system_jurnal, system_sales, system_pur, system_pay) VALUES('" + jTextField1.getText()
                    + "-" + jTextField2.getText() + "-1',1,1,1,1)");
            System.out.println("INSERT INTO SYSTEM(system_date, system_jurnal, system_sales, system_pur,system_pay) VALUES('" + jTextField1.getText()
                    + "-" + jTextField2.getText() + "-1',1,1,1,1)");

            DataBase.date = jTextField1.getText() + "-" + jTextField2.getText();
            DataBase.jurnalDate = jTextField1.getText() + "-" + jTextField2.getText();
            DataBase.jurnalId = 1;
            DataBase.salesId = 1;
            DataBase.purId = 1;
            DataBase.payId = 1;
            loadJurnal++;
            System.out.println(DataBase.date);
            homeButton();
//            setIcon("DATE : " + DataBase.jurnalDate, "JURNAL");
            //icon detail
            Detail.setCash(DataBase.date);
            Detail.setBank(DataBase.date);
            //
            add(jurnal, BorderLayout.CENTER);
            jurnal.setVisible(true);
            Detail.setIconDetail("JURNAL");
            Detail.setJurnalDateDetail("DATE : " + DataBase.date);

        }
        if (menu == 1) { // use existing juranl
            dEditorJurnal.setVisible(false);

            DataBase.date = jTextField1.getText() + "-" + jTextField2.getText();
            DataBase.jurnalDate = jTextField1.getText() + "-" + jTextField2.getText();
            DataBase.setJurnalId();
            loadJurnal++;

            System.out.println(DataBase.date);
            homeButton();
//            setIcon("DATE : " + DataBase.jurnalDate, "JURNAL");
            //icon detail
            Detail.setCash(DataBase.date);
            Detail.setBank(DataBase.date);
            //
            add(jurnal, BorderLayout.CENTER);
            jurnal.setVisible(true);
            Detail.setIconDetail("JURNAL");
            Detail.setJurnalDateDetail("DATE : " + DataBase.date);
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        JFrame frame = new JFrame();
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        int height = screenSize.height;
//        int width = screenSize.width;
//        frame.setSize(width / 2, height / 2);
//        System.out.println(height);
//        System.out.println(width);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main m = new main();
                m.setLocationRelativeTo(null);
                m.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog dEditorJurnal;
    private javax.swing.JDialog dMenuJurnal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
