
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Leonardy
 */
public class ProfitLoss extends javax.swing.JPanel {

    String date;
    float finalValue = 0;

    /**
     * Creates new form ProfitLoss
     */
    public void setTf() {
        jTextField1.setText(DataBase.date);
    }

    public float getProfitLoss(String date) {
        setProfitLoss(date);
        return finalValue;
    }

    public ProfitLoss() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CHART NAME", "PRICE", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(1);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CHART NAME", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CHART NAME", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setText("SALES");

        jLabel2.setText("COGS");

        jLabel3.setText("EXPENDITURE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("NET PROFIT : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jLabel1))
                        .addGap(415, 415, 415)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2)
                        .addGap(572, 572, 572)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 386, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void setProfitLoss(String date) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel model2 = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        ArrayList<String> chartList = new ArrayList<>();
        Statement st = DataBase.getStatement();
        ResultSet rs;
        int totalSales = 0, totalFinalSales = 0, totalCogs = 0;
        float totalFinalCogs = 0, totalExpend = 0, totalFinalExpend = 0;
        try {
            st = DataBase.getStatement();
            rs = st.executeQuery("select distinct chart_name from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_id like '4%'");
            System.out.println("select distinct chart_name from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_id like '4%'");
            while (rs.next()) {
                chartList.add(rs.getString("chart_name"));
            }
            for (String a : chartList) {
                rs = st.executeQuery("select chart_name, sum(credit)-sum(debit) from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_name like '" + a + "'");
                System.out.println("select chart_name, sum(credit)-sum(debit) from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_name like '" + a + "'");
                while (rs.next()) {
                    int sales = rs.getInt("sum(credit)-sum(debit)");
                    totalSales += sales;
                    model.addRow(new Object[]{a, totalSales});
                    totalFinalSales += totalSales;
                    totalSales = 0;
                }
            }
            model.addRow(new Object[]{"SUM", "", totalFinalSales});
            model.addRow(new Object[]{});
            model.addRow(new Object[]{"COGS"});
            chartList.clear();
            //for cogs
            rs = st.executeQuery("select distinct chart_name from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_id like '5%'");
            System.out.println("select distinct chart_name from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_id like '5%'");
            while (rs.next()) {
                chartList.add(rs.getString("chart_name"));
            }
            for (String a : chartList) {
                rs = st.executeQuery("select chart_name, sum(debit)-sum(credit) from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_name like '" + a + "'");
                System.out.println("select chart_name, sum(debit)-sum(credit) from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_name like '" + a + "'");
                while (rs.next()) {
                    System.out.println(a);
                    int cogs = rs.getInt("sum(debit)-sum(credit)");
                    totalCogs += cogs;
                    model.addRow(new Object[]{a, totalCogs});
                    totalFinalCogs += totalCogs;
                    totalCogs = 0;
                    System.out.println(totalFinalCogs);
                }
            }
            Inventory in = new Inventory();
            int aa = (int) in.getTotalFinal(date);
            model.addRow(new Object[]{"ending inventory", aa});
            totalFinalCogs = (totalFinalCogs - aa);
            System.out.println(totalFinalCogs + in.getTotalFinal(date));
            model.addRow(new Object[]{"SUM", "", totalFinalCogs});
            model.addRow(new Object[]{});
            model.addRow(new Object[]{"OPERASIONAL EXPENDICUTE"});
            chartList.clear();

            //for expenditure
            rs = st.executeQuery("select distinct chart_name from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_id like '6%'");
            System.out.println("select distinct chart_name from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_id like '6%'");
            while (rs.next()) {
                chartList.add(rs.getString("chart_name"));
            }
            for (String a : chartList) {
                rs = st.executeQuery("select chart_name, sum(debit)-sum(credit) from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_name like '" + a + "'");
                System.out.println("select chart_name, sum(debit)-sum(credit) from jurnal natural join chart where jurnal_date like '" + date + "-%' and chart_name like '" + a + "'");
                while (rs.next()) {
                    int expend = rs.getInt("sum(debit)-sum(credit)");
                    totalExpend += expend;
                    model.addRow(new Object[]{a, "", totalExpend});
                    totalFinalExpend += totalExpend;
                    totalExpend = 0;
                }
            }
            model.addRow(new Object[]{"SUM", totalFinalExpend});
            model.addRow(new Object[]{});
            chartList.clear();
            finalValue = totalFinalSales - totalFinalCogs - totalFinalExpend;
            model.addRow(new Object[]{"", "TOTAL", finalValue});
            Double d = new Double(finalValue);
            jLabel5.setText(Double.toString(d));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        date = jTextField1.getText();
        setProfitLoss(date);
        DataBase.date = date;
        finalValue = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        date = jTextField1.getText();
        setProfitLoss(date);
        DataBase.date = date;
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
