
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.GridLayout;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Leonardy
 */
public class test2 extends javax.swing.JFrame {

    private javax.swing.JComboBox[] combo1; //array of JComboBoxes
    private javax.swing.JComboBox[] combo2; //array of JComboBoxes
    private javax.swing.JTextField[] text1; //array of JTextFields
    private int count = -1;
    private int max_row = 10;
    private int empty_count = 0;

    private void combo1_combo2_text1_array() {
        combo1 = new JComboBox[10];
        combo2 = new JComboBox[10];
        text1 = new JTextField[10];
    }

    /**
     * Creates new form main
     */
    public test2() {
        initComponents();
        combo1_combo2_text1_array();

    }

    private void addrowActionPerformed(java.awt.event.ActionEvent evt) {  // Add one row at a time                                     
        if (count == max_row - 1) {
            JOptionPane.showMessageDialog(null, "Maximum of 10 rows can be added", "Failed!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        count++;
        combo1[count] = new javax.swing.JComboBox();
        for (int i = 1; i <= 5; i++) {
            combo1[count].addItem("Item " + i);
        }
        combo2[count] = new javax.swing.JComboBox();
        for (int i = 1; i <= 5; i++) {
            combo2[count].addItem("Item " + i);
        }
        text1[count] = new javax.swing.JTextField();
        jPanel4.setLayout(new GridLayout(0, 3, 20, 20));
        jPanel4.add(combo1[count]);
        jPanel4.add(combo2[count]);
        jPanel4.add(text1[count]);
        jPanel4.revalidate();
        jPanel4.repaint();
    }

    private void removerowActionPerformed(java.awt.event.ActionEvent evt) {   // Remove Row Action                                       
        if (count > -1) { // Deleting one row at a time
            jPanel4.remove(combo1[count]);
            jPanel4.remove(combo2[count]);
            jPanel4.remove(text1[count]);
            count--;
            jPanel4.revalidate();
            jPanel4.repaint();
        }
    }

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {   // Cancel Button Action                                     
        System.exit(0);
    }

//    private void resetActionPerformed(java.awt.event.ActionEvent evt) { //Reset Button Action                                     
//        jTextField1.setText("");
//        for (int i = count; i > -1; i--) {
//            jPanel4.remove(combo1[i]);
//            jPanel4.remove(combo2[i]);
//            jPanel4.remove(text1[i]);
//            jPanel4.revalidate();
//            jPanel4.repaint();
//        }
//        count = -1;
//    }
//
//    private void submitActionPerformed(java.awt.event.ActionEvent evt) {
//        if (jTextField1.getText().length() == 0) // Submit button for the register form
//        {
//            JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields", "Failed!!", JOptionPane.ERROR_MESSAGE);
//        } else if (count > -1) {
//            for (int i = 0; i <= count; i++) {
//                if (text1[count].getText().length() == 0) {
//                    empty_count++;
//                }
//            }
//            if (empty_count > 0) {
//                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields", "Failed!!", JOptionPane.ERROR_MESSAGE);
//                empty_count = 0; // resetting the count
//            } else {
//                JOptionPane.showMessageDialog(null, "No database connection for this application", "Failed!!", JOptionPane.ERROR_MESSAGE);
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "No database connection for this application", "Failed!!", JOptionPane.ERROR_MESSAGE);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        JFrame f = new JFrame();
//        JButton b1 = new JButton("NORTH");
//        JButton b2 = new JButton("SOUTH");
//        JButton b3 = new JButton("EAST");
//        JButton b4 = new JButton("WEST");
//        JButton b5 = new JButton("CENTER");
//        JPanel jp = new JPanel();
////        jp.setLayout(new BoxLayout(b3,1));
//        f.add(b1, BorderLayout.NORTH);
//        f.add(b2, BorderLayout.SOUTH);
//        f.add(b3, BorderLayout.EAST);
//        f.add(b4    , BorderLayout.WEST);
//        f.add(b5, BorderLayout.CENTER);
//
//        f.setSize(300, 300);
//        f.setVisible(true);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
